// ==== RS3ProjectXUpdater offsets 950-1 ====
// !!! DRIFT DETECTED — offsets that CHANGED vs previous build:
//   ONPC.SHOW_AS_IMPORTANT: 0x1100 -> 0x1120
//   OWorld.PROJECTION_MATRIX: 0x13200 -> 0x13220
//   OWorld.VIEW_MATRIX: 0x13100 -> 0x13120
//   OWorld.MAPSQUARE_X_OFFSET: 0x13fd4 -> 0x14034
//   OWorld.MAPSQUARE_Y_OFFSET: 0x13fd8 -> 0x14038
//   OWorld.MAPSQUARES_VECTOR: 0x14020 -> 0x14080
//   OClient.SCENE_MANAGER: 0x19558 -> 0x199d0
//   OClient.MAIN_STATE: 0x19b28 -> 0x19fa0
//   OClient.HINTTRAIL_LIST: 0x19480 -> 0x198f8
//   OClient.HINTARROW_LIST: 0x19478 -> 0x198f0
//   OClient.BUILD_AREA_VECTOR: 0x193d8 -> 0x19850
//   OInputState.KEY_DOWN_MAP_ROOT: 0x1686730 -> 0xda6020
//   OGlobal.MONOTONIC_CLOCK_MS: 0x146f998 -> 0xfb8268
//
// (16 further anchor(s) unresolved — drift undetermined for those.)
// Generated by RS3ProjectXUpdater for 950-1 — copy/paste into Offsets.kt.

object OFunctions { // 35/48 resolved
    const val CONNECTIONMANAGER_TCPIN = 0x000ea230L   //950-1 — jag::ConnectionManager::TcpIn
    const val CLIENT_SETMAINSTATE = 0x000267e0L   //950-1 — jag::Client::SetMainState
    // STATTABLE_UPDATESTAT — UNRESOLVED (jag::game::StatTable::UpdateStat not sig-matched)
    // CLIENT_MAINLOGIC — UNRESOLVED (jag::Client::MainLogic not sig-matched)
    // SERVERPROT_DECODE_UPDATE_INV_PARTIAL — UNRESOLVED (jag::PacketHandlers::UpdateInvPartial not sig-matched)
    // SERVERPROT_DECODE_UPDATE_INV_FULL — UNRESOLVED (jag::PacketHandlers::UpdateInvFull not sig-matched)
    const val CHATHISTORY_ADDCHAT_HOOKABLE = 0x0014c200L   //950-1 — jag::ChatHistory::AddChat_hookable
    const val PLAYERVARDOMAIN_SETVARVALUEFROMSERVER = 0x002eafb0L   //950-1 — jag::game::PlayerVarDomain::SetVarValueFromServer
    const val PLAYERVARDOMAIN_SETVARVALUE = 0x002eaeb0L   //950-1 — jag::game::PlayerVarDomain::SetVarValue
    const val CLIENTVARDOMAIN_SETVARVALUE = 0x00154070L   //950-1 — jag::ClientVarDomain::SetVarValue
    const val MINIMENU_DOACTION = 0x00167d50L   //950-1 — jag::MiniMenu::DoAction
    // INTERFACEMANAGER_IFBUTTONXINNER — UNRESOLVED (jag::InterfaceManager::IfButtonXInner not sig-matched)
    const val PROJECTILELIST_ADD = 0x00127940L   //950-1 — jag::ProjectileList::Add
    // ENTITY_ENTITY — UNRESOLVED (jag::game::Entity::Entity not sig-matched)
    const val ENTITY_ENTITY_DESTRUCT = 0x0010ec20L   //950-1 — jag::game::Entity::~Entity
    const val INVENTORYMANAGER_GETINVENTORY = 0x003148f0L   //950-1 — jag::game::InventoryManager::GetInventory
    const val HITMARKSANDHEADBARS_ADDHEADBAR = 0x0037c470L   //950-1 — jag::HitmarksAndHeadbars::AddHeadbar
    const val HITMARKSANDHEADBARS_ADDHITMARK = 0x0037be50L   //950-1 — jag::HitmarksAndHeadbars::AddHitmark
    const val INPUT_INPUT_ONKEYDOWNINNER = 0x00033720L   //950-1 — jag::input::Input::OnKeyDownInner
    const val INPUT_INPUT_ONKEYUPINNER = 0x00033a80L   //950-1 — jag::input::Input::OnKeyUpInner
    // SCRIPTRUNNER_EXECUTEHOOKINNER — UNRESOLVED (jag::ScriptRunner::ExecuteHookInner not sig-matched)
    const val SCRIPTRUNNER_EXECUTESCRIPT = 0x0008dd70L   //950-1 — jag::ScriptRunner::ExecuteScript
    const val SCRIPTRUNNER_GETCLIENTSCRIPTSTATE = 0x0008dca0L   //950-1 — jag::ScriptRunner::GetClientScriptState
    const val SCRIPTRUNNER_CONTINUESCRIPT = 0x0008df90L   //950-1 — jag::ScriptRunner::ContinueScript
    const val SCRIPTRUNNER_GET_BY_ID = 0x0003a680L   //950-1 — jag::ClientScriptHelpers::GetByID
    const val INPUT_INPUT_ONMOUSEMOTION = 0x00881070L   //950-1 — jag::input::Input::OnMouseMotion
    const val INPUT_INPUT_ONLEFTBUTTONDOWN = 0x00880bc0L   //950-1 — jag::input::Input::OnLeftButtonDown
    const val INPUT_INPUT_ONLEFTBUTTONUP = 0x00880ce0L   //950-1 — jag::input::Input::OnLeftButtonUp
    const val INPUT_INPUT_ONSCROLLWHEEL = 0x008811a0L   //950-1 — jag::input::Input::OnScrollWheel
    const val INPUT_INPUT_ONKEYCHARINNER = 0x00033bc0L   //950-1 — jag::input::Input::OnKeyCharInner
    const val EVENTLISTENERS_CALLLISTENERS_FF = 0x0087e9f0L   //950-1 — jag::EventListeners::CallListeners_ff
    // INPUTSTATE_ISKEYDOWN — UNRESOLVED (jag::input::InputState::IsKeyDown not sig-matched)
    const val TCPCONNECTIONMESSAGE_INIT = 0x0008e6a0L   //950-1 — jag::game::TcpConnectionMessage::Init
    const val TCPCONNECTIONMESSAGE_INIT_INCOMING = 0x001000b0L   //950-1 — jag::game::TcpConnectionMessage::InitIncoming
    // SENDCLIENTMESSAGE — UNRESOLVED (jag::Packet::SendClientMessage not sig-matched)
    // REBUILD_NORMAL_HANDLER — UNRESOLVED (jag::PacketHandlers::RebuildNormal not sig-matched)
    const val BUILD_AREA_INIT = 0x0040a280L   //950-1 — jag::game::RebuildSceneEntry::Reset
    const val INTERFACEMANAGER_DRAWCOMPONENTLIST = 0x001a8690L   //950-1 — jag::InterfaceManager::DrawComponentList
    // CLIENTPROT_SENDEVENTMOUSECLICK — UNRESOLVED (jag::ClientProt::SendEventMouseClick not sig-matched)
    const val APPLY_LOC_CHANGE = 0x0011e680L   //950-1 — jag::game::ApplyLocChange
    const val CLIENTERROR_REPORTERROR = 0x003fc620L   //950-1 — jag::game::ClientError::ReportError
    const val CLIENTSTREAM_READ = 0x00641850L   //950-1 — jag::ClientStream::Read
    const val CLIENTSTREAM_WRITE = 0x00641b90L   //950-1 — jag::ClientStream::Write
    const val SERVERCONNECTION_FLUSHCLIENTMESSAGES = 0x002f46a0L   //950-1 — jag::game::ServerConnection::FlushClientMessages
    const val EVENTLISTENERS_DISPATCHMOUSEEVENTWITHSOURCE = 0x0087f0c0L   //950-1 — jag::input::EventListeners::DispatchMouseEventWithSource
    // CLIENTPROT_SENDNATIVEMOUSECLICK — UNRESOLVED (jag::ClientProt::SendNativeMouseClick not sig-matched)
    const val CLIENTPROT_FLUSHMOUSEPROTSENDER = 0x0014bae0L   //950-1 — jag::ClientProt::FlushMouseProtSender
    // CLIENTPROT_FLUSHPERTICK — UNRESOLVED (jag::ClientProt::FlushPerTick not sig-matched)
}

// ---- OGlobal + struct-field offsets (from anchors), grouped by object ----

object OGlobal {
    // CLIENT — UNRESOLVED (anchor-not-located)
    // MONOTONIC_CLOCK_MS — UNRESOLVED (platform-scoped to linux-x86_64)
    const val MONOTONIC_CLOCK_MS = 0xfb8268L   //950-1 (was 0x146f998) — MEDIUM *** CHANGED ***
}

object ONPC {
    // CURRENT_HP — UNRESOLVED (anchor-not-located)
    const val SHOW_AS_IMPORTANT = 0x1120L   //950-1 (was 0x1100) — HIGH *** CHANGED ***
}

object OWorld {
    // VIEW_MATRIX — UNRESOLVED (platform-scoped to linux-x86_64)
    const val PROJECTION_MATRIX = 0x13220L   //950-1 (was 0x13200) — MEDIUM *** CHANGED ***
    const val VIEW_MATRIX = 0x13120L   //950-1 (was 0x13100) — MEDIUM *** CHANGED ***
    // HEIGHT_MAP — UNRESOLVED (recipe-error: back_scan not found for jag::game::HeightMap::GetFineHeight)
    const val MAPSQUARE_X_OFFSET = 0x14034L   //950-1 (was 0x13fd4) — MEDIUM *** CHANGED ***
    const val MAPSQUARE_Y_OFFSET = 0x14038L   //950-1 (was 0x13fd8) — MEDIUM *** CHANGED ***
    const val MAPSQUARE_X_MAX = 0x1403cL   //950-1 (was null) — MEDIUM
    const val MAPSQUARE_Y_MAX = 0x14040L   //950-1 (was null) — MEDIUM
    const val MAPSQUARES_VECTOR = 0x14080L   //950-1 (was 0x14020) — MEDIUM *** CHANGED ***
    // ROOT_GRAPH_NODE — UNRESOLVED (platform-scoped to linux-x86_64)
    const val ROOT_GRAPH_NODE = 0x10170L   //950-1 (was 0x10170) — MEDIUM
    // LINK_MAP — UNRESOLVED (recipe-error: back_scan not found for jag::game::LinkMap::ReadTileFlags)
}

object OMapSquare {
    // COMPOSITE_DATA — UNRESOLVED (platform-scoped to linux-x86_64)
    // COMPOSITE_DATA.msvc — UNRESOLVED (anchor-not-located)
    // LOCATION_CONTAINERS — UNRESOLVED (anchor-not-located)
}

object OPathingEntity {
    // HITMARKS_AND_HEADBARS — UNRESOLVED (recipe-error: back_scan not found for jag::HitmarksAndHeadbars::AddHeadbar)
}

object OClient {
    // NPC_MANAGER — UNRESOLVED (manager-class-no-consensus:jag::NPCList)
    // CONNECTION_MANAGER — UNRESOLVED (manager-class-no-consensus:jag::ConnectionManager)
    const val SCENE_MANAGER = 0x199d0L   //950-1 (was 0x19558) — MEDIUM *** CHANGED ***
    // INTERFACE_MANAGER — UNRESOLVED (platform-scoped to linux-x86_64)
    // CAMERA — UNRESOLVED (platform-scoped to linux-x86_64)
    // BUILD_AREA_VECTOR — UNRESOLVED (platform-scoped to linux-x86_64)
    // INVENTORY_MANAGER — UNRESOLVED (manager-class-no-consensus:jag::game::InventoryManager)
    // PLAYER_VAR_DOMAIN — UNRESOLVED (manager-class-no-consensus:jag::game::PlayerVarDomain)
    const val MAIN_STATE = 0x19fa0L   //950-1 (was 0x19b28) — MEDIUM *** CHANGED ***
    // PROJECTILE_LIST — UNRESOLVED (recipe-error: back_scan not found for jag::ProjectileList::Add)
    // CAMERA.msvc — UNRESOLVED (recipe-error: back_scan not found for jag::game::Camera::ForceAngle)
    const val HINTTRAIL_LIST = 0x198f8L   //950-1 (was 0x19480) — MEDIUM *** CHANGED ***
    const val HINTARROW_LIST = 0x198f0L   //950-1 (was 0x19478) — MEDIUM *** CHANGED ***
    // INTERFACE_MANAGER.msvc — UNRESOLVED (anchor-not-located)
    const val BUILD_AREA_VECTOR = 0x19850L   //950-1 (was 0x193d8) — MEDIUM *** CHANGED ***
}

object OMainLogicManager {
    // STAT_TABLE — UNRESOLVED (anchor-not-located)
    // MOVE_BUFFER_BASE — UNRESOLVED (platform-scoped to linux-x86_64)
    // MOVE_BUFFER_BASE.msvc — UNRESOLVED (anchor-not-located)
}

object OAnimation {
    // CURRENT_FRAME — UNRESOLVED (platform-scoped to linux-x86_64)
    const val CURRENT_FRAME = 0x24L   //950-1 (was 0x24) — MEDIUM
}

object OInputState {
    // KEY_DOWN_MAP_ROOT — UNRESOLVED (platform-scoped to linux-x86_64)
    const val KEY_DOWN_MAP_ROOT = 0xda6020L   //950-1 (was 0x1686730) — MEDIUM *** CHANGED ***
    const val KEY_DOWN_MAP_ANCHOR = 0xda6010L   //950-1 (was null) — MEDIUM
    const val KEY_NODE_VK = 0x20L   //950-1 (was null) — MEDIUM
    const val KEY_NODE_PRESSED = 0x24L   //950-1 (was null) — MEDIUM
}
